sliders = VISUALIZED_DATA VOXEL_AREA RT_API RT_STEPS STUPID_RT_BIAS_IRIS_BUG RT_NIAVE_STEP_SIZE SUN_WIDTH TEXTURES_IN_RT


#//shader's settings screen 
screen.columns = 2
screen=[help]  [Voxelizing] <empty> <empty> RT_API RT_STEPS RT_NIAVE_STEP_SIZE STUPID_RT_BIAS_IRIS_BUG <empty> <empty> RAYTRACING_VIEW RT_SHADOWS_IN_RT_DEBUG_VIEW SOFT_RT_SHADOWS RT_SHADOWS_IN_GBUFFERS <empty> <empty> SUN_WIDTH TEXTURES_IN_RT USE_TEXTURE_NORMALS IRON_MIRRORS

screen.Voxelizing = VISUALIZED_DATA DEBUG_ALIGHNMENT VOXEL_AREA VOXEL_POSITION_RECONSTRUCTION_METHOD WHERE_TO_VOXELIZE VOXELIZED_DEBUG_VIEW 





#//enable custom images. we are using a 3d custom image to store our voxel data
iris.features.required = CUSTOM_IMAGES

#//make the shadow pass run for voxelizing, even if we don't sample it. Iris and Optifine will otherwise not run the shadow pass unless we sample it
shadow.enabled=true

#//prevent sampling darker corners of blocks
separateAo=true

#//don't cull offscreen things in the voxelizing range. this range is set in a composite shader, because that's where iris wants it.
shadow.culling=reversed



#//Textures & Images

#//create our 3d image, 
#//   here's the format:
#//   image. < name for layout > = <name as sampler> <format stuff>                 <clear every frame> <size is relative to screen size> <size x,y,z>
#//   image.cimage1              =       cSampler1   RED_INTEGER R32UI UNSIGNED_INT true false 128 128 128
#if VOXEL_AREA == 128
	image.cimage1 = cSampler1 RED_INTEGER R32UI UNSIGNED_INT true false 128 128 128
#endif
#if VOXEL_AREA == 64
	image.cimage1 = cSampler1 RED_INTEGER R32UI UNSIGNED_INT true false 64 64 64
#endif
#if VOXEL_AREA == 32
	image.cimage1 = cSampler1 RED_INTEGER R32UI UNSIGNED_INT true false 32 32 32
#endif

##texture.noisetex = stuff/noise/blue/1.png
customTexture.blue_noise_tex = stuff/noise/blue/1.png

#if TEXTURES_IN_RT > 0
	customTexture.atlas_a = minecraft:textures/atlas/blocks.png
	image.c_image4_voxel_scene = cSamplerVoxelScene RED_INTEGER R32UI UNSIGNED_INT true false 256 256 256
#endif




#//Blend States
blend.gbuffers_terrain.colortex1=off
blend.gbuffers_water.colortex1=off
blend.dh_water.colortex1=off
blend.dh_terrain.colortex1=off
blend.physics_ocean.colortex1=off
blend.gbuffers_hand.colortex1=off
blend.gbuffers_hand_water.colortex1=off
blend.gbuffers_entities.colortex1=off
blend.gbuffers_weather.colortex1=off
blend.gbuffers_basic.colortex1=off
blend.gbuffers_textured.colortex1=off
blend.gbuffers_textured_lit.colortex1=off

blend.gbuffers_terrain.colortex2=off
blend.gbuffers_water.colortex2=off
blend.dh_water.colortex2=off
blend.dh_terrain.colortex2=off
blend.physics_ocean.colortex2=off
blend.gbuffers_hand.colortex2=off
blend.gbuffers_hand_water.colortex2=off
blend.gbuffers_entities.colortex2=off
blend.gbuffers_weather.colortex2=off
blend.gbuffers_basic.colortex2=off
blend.gbuffers_textured.colortex2=off
blend.gbuffers_textured_lit.colortex2=off

blend.gbuffers_terrain.colortex3=off
blend.gbuffers_water.colortex3=off
blend.dh_water.colortex3=off
blend.dh_terrain.colortex3=off
blend.physics_ocean.colortex3=off
blend.gbuffers_hand.colortex3=off
blend.gbuffers_hand_water.colortex3=off
blend.gbuffers_entities.colortex3=off
blend.gbuffers_weather.colortex3=off
blend.gbuffers_basic.colortex3=off
blend.gbuffers_textured.colortex3=off
blend.gbuffers_textured_lit.colortex3=off

blend.gbuffers_terrain.colortex4=off
blend.gbuffers_water.colortex4=off
blend.dh_water.colortex4=off
blend.dh_terrain.colortex4=off
blend.physics_ocean.colortex4=off
blend.gbuffers_hand.colortex4=off
blend.gbuffers_hand_water.colortex4=off
blend.gbuffers_entities.colortex4=off
blend.gbuffers_weather.colortex4=off
blend.gbuffers_basic.colortex4=off
blend.gbuffers_textured.colortex4=off
blend.gbuffers_textured_lit.colortex4=off

blend.gbuffers_terrain.colortex5=off
blend.gbuffers_water.colortex5=off
blend.dh_water.colortex5=off
blend.dh_terrain.colortex5=off
blend.physics_ocean.colortex5=off
blend.gbuffers_hand.colortex5=off
blend.gbuffers_hand_water.colortex5=off
blend.gbuffers_entities.colortex5=off
blend.gbuffers_weather.colortex5=off
blend.gbuffers_basic.colortex5=off
blend.gbuffers_textured.colortex5=off
blend.gbuffers_textured_lit.colortex5=off

